version: "3.9"
services:
  minecraft:
    build: .
    image: ilarioras/minecraft
    ports:
      - "8080:8080"
      - "25565:25565"
    volumes:
      - "./banned-ips.json:/minecraft/banned-ips.json:z"
      - "./banned-players.json:/minecraft/banned-players.json:z"
      - "./Bukkit:/minecraft/Bukkit:z"
      - "./bukkit.yml:/minecraft/bukkit.yml:z"
      - "./commands.yml:/minecraft/commands.yml:z"
      - "./CraftBukkit:/minecraft/CraftBukkit:z"
      - "./eula.txt:/minecraft/eula.txt:z"
      - "./help.yml:/minecraft/help.yml:z"
      - "./logs:/minecraft/logs:z"
      - "./ops.json:/minecraft/ops.json:z"
      - "./permissions.yml:/minecraft/permissions.yml:z"
      - "./plugins:/minecraft/plugins:z"
      - "./server.properties:/minecraft/server.properties:z"
      - "./spigot.yml:/minecraft/spigot.yml:z"
      - "./usercache.json:/minecraft/usercache.json:z"
      - "./whitelist.json:/minecraft/whitelist.json:z"
      - "./world:/minecraft/world:z"
      - "./world_nether:/minecraft/world_nether:z"
      - "./world_the_end:/minecraft/world_the_end:z"
    deploy:
      resources:
        limits:
          memory: "6GB"
      restart_policy:
        condition: on-failure
