version: "3.9"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  minecraft:
    image:  ilarioras/minecraft
    container_name: spigot
    ports:
      - "8080:8080"
      - "25565:25565"
    volumes:
      - "./banned-ips.json:/minecraft/banned-ips.json:z"
      - "./banned-players.json:/minecraft/banned-players.json:z"
      - "./Bukkit:/minecraft/Bukkit:z"
      - "./bukkit.yml:/minecraft/bukkit.yml:z"
      - "./commands.yml:/minecraft/commands.yml:z"
      - "./CraftBukkit:/minecraft/CraftBukkit:z"
      - "./eula.txt:/minecraft/eula.txt:z"
      - "./help.yml:/minecraft/help.yml:z"
      - "./logs:/minecraft/logs:z"
      - "./ops.json:/minecraft/ops.json:z"
      - "./permissions.yml:/minecraft/permissions.yml:z"
      - "./plugins:/minecraft/plugins:z"
      - "./server.properties:/minecraft/server.properties:z"
      - "./spigot.yml:/minecraft/spigot.yml:z"
      - "./usercache.json:/minecraft/usercache.json:z"
      - "./whitelist.json:/minecraft/whitelist.json:z"
      - "./world:/minecraft/world:z"
      - "./world_nether:/minecraft/world_nether:z"
      - "./world_the_end:/minecraft/world_the_end:z"
    deploy:
      resources:
        limits:
          memory: "6GB"
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - "./prometheus:/etc/prometheus:z"
      - "prometheus_data:/prometheus_data"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100