{
 "title": "Minecraft",
 "description": "Stuff from Minecraft",
 "tags": [ "minecraft" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Container total memory usage",
   "type": "gauge",
   "description": "Memory used after GC",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_Shenandoah_Cycles_LastGcInfo_memoryUsageAfterGc_used)/(sum(jvm_memory_bytes_max)/0.8)",
     "legendFormat": "{{ key }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"ilarioras/minecraft\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Shenandoah_Cycles_LastGcInfo_memoryUsageAfterGc_used",
     "legendFormat": "{{ key }}"
    }
   ]
  },
  {
   "title": "GC cycle time",
   "type": "heatmap",
   "description": "How long each GC cycle took. Lower is better.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Shenandoah_Cycles_LastGcInfo_duration"
    }
   ]
  },
  {
   "title": "Server tick time",
   "type": "heatmap",
   "description": "Should stay under 50 ms, or there might be noticeable lag in game.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "net_minecraft_server_v1_16_R3_Server_averageTickTime",
     "legendFormat": "Server tick time"
    }
   ]
  },
  {
   "title": "Java Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_state", "legendFormat": "{{ state }}" }
   ]
  },
  {
   "title": "Something Shenandoah",
   "type": "graph",
   "description": "No idea what this means.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_Shenandoah_Cycles_LastGcInfo_memoryUsageBeforeGc_committed[5m])",
     "legendFormat": "{{ key }}"
    }
   ]
  }
 ]
}